apiVersion: v1
kind: ReplicationController
metadata:
  name: mem-besteffort
spec:
  replicas: 1
  selector:
    app: memhog
  template:
    metadata:
      name: mem-besteffort
      labels:
        app: memhog
    spec:
      containers:
      - name: mem-besteffort
        image: lorel/docker-stress-ng
        args: ["--class", "memory", "--sequential", "8", "--vm-hang", "0"]
        # qos best effort - no limits or requests specified
